### ISSUE TITLE
Package extent

### ISSUE THREAD

**Issue by PascalIrz** [juanfonsecaLS1/telraamR#3]
Hi Juan, thanks for sharing your work.
I also query the Telraam API from R. The aim is to feed a shiny dataviz app.
Do you intend to add to your package some functions for the data processing, or will you keep it focused on the querries?
Cheers.
Pascal

**Comment by juanfonsecaLS1** [comment]
Hi Pascall, thanks for you interest. I am focusing on providing functions for the basic queries at the moment. I do have plans to add some basic data processing and visualisation functions, that I will come in the near future (I think next month or so)
